<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">  
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>  
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
    <title>Calculator</title>
</head>
<body>
    <header>
        
    </header>
    <main>
        <section>
            <h2>Opération :</h2>
            <form action="index.php" method="post">
                <fieldset>
                    <label for="nb-1">Votre premier nombre :</label>
                    <input type="number" id="nb-1" name="firstNb">
                </fieldset>
                <fieldset>
                    <label for="nb-2">Votre second nombre :</label>
                    <input type="number" id="nb-2" name="secondNb">
                </fieldset>
                <fieldset>
                    <label for="operation-select">Choisissez une opération :</label>
                    <select name="operations" id="operation-select">
                        <option value="">--Choisissez une opération --</option>
                        <option value="add">Addition</option>
                        <option value="substract">Soustraction</option>
                        <option value="multiply">Multiplication</option>
                        <option value="divide">Division</option>
                        <option value="modulo">Modulo</option>
                        <option value="power">Puissance</option>
                        <option value="factorial">Factorielle</option>
                    </select>
                </fieldset>
                <fieldset>
                    <label for="geometry-select">Choisissez une surface :</label>
                    <select name="geometry" id="geometry-select">
                        <option value="">--Choisissez une opération --</option>
                        <option value="rectangle_surface">Rectangle</option>
                        <option value="rectangle_triangle_surface">Triangle rectangle</option>
                        <option value="basic_triangle_surface">Triangle quelconque</option>
                        <option value="disk_surface">Disque</option>
                    </select>
                </fieldset>
                <fieldset>
                    <input type="submit" id="sub-btn" value="Calculer">
                </fieldset>
            </form>
        </section>
        <section>
            <h2>Résultat :</h2>
            <h3>
            <?php 
            
                if(isset($result))
                    {
                        echo $result;
                    }
            ?>
            </h3>
        </section>
    </main>
    <footer>
        
    </footer>
</body>
</html>